-- =====================================================================
-- V1 — Baseline schema
-- ---------------------------------------------------------------------
-- Mirrors the original Hibernate-generated schema (users + tasks) so
-- that Flyway can take over as the single source of truth.
--
-- On an EXISTING database (previously created by `ddl-auto: update`),
-- `spring.flyway.baseline-on-migrate=true` marks this version as the
-- baseline and skips it, then applies V2+.  On a FRESH database this
-- script creates the tables.
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)                NOT NULL,
    email       VARCHAR(150)                NOT NULL,
    password    VARCHAR(255)                NOT NULL,          -- BCrypt hash
    role        VARCHAR(20)                 NOT NULL DEFAULT 'ROLE_USER',
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150)                NOT NULL,
    description  TEXT                        NULL,
    priority     VARCHAR(20)                 NOT NULL DEFAULT 'MEDIUM',
    status       VARCHAR(20)                 NOT NULL DEFAULT 'TODO',
    due_date     DATE                        NULL,
    user_id      BIGINT                      NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tasks_user     ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);
