-- =====================================================================
-- V3 — Advanced auth: account flags + token/audit tables
-- =====================================================================

-- ---------------------------------------------------------------------
-- users: account activation + email verification flags
-- ---------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled        BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Existing accounts predate email verification; treat them as verified so
-- they are not locked out by the new login check.
UPDATE users SET email_verified = TRUE WHERE email_verified = FALSE;

-- ---------------------------------------------------------------------
-- refresh_tokens (opaque, hashed, rotating)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                      NOT NULL,
    token_hash  VARCHAR(64)                 NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked     BOOLEAN                     NOT NULL DEFAULT FALSE,
    user_agent  VARCHAR(255)                NULL,
    ip_address  VARCHAR(45)                 NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------
-- email_verification_tokens
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                      NOT NULL,
    token_hash  VARCHAR(64)                 NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used        BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_evt_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_evt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_evt_user ON email_verification_tokens (user_id);

-- ---------------------------------------------------------------------
-- password_reset_tokens
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                      NOT NULL,
    token_hash  VARCHAR(64)                 NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used        BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_prt_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_prt_user ON password_reset_tokens (user_id);

-- ---------------------------------------------------------------------
-- login_history (audit of login attempts)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS login_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT                      NULL,
    email          VARCHAR(150)                NOT NULL,
    success        BOOLEAN                     NOT NULL,
    failure_reason VARCHAR(100)                NULL,
    ip_address     VARCHAR(45)                 NULL,
    user_agent     VARCHAR(255)                NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_login_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_login_user    ON login_history (user_id);
CREATE INDEX IF NOT EXISTS idx_login_created ON login_history (created_at);
