-- =====================================================================
-- V5 — Advanced user profiles: profile info, notification preferences,
--      and account activity history.
-- =====================================================================

-- ---------------------------------------------------------------------
-- user_profiles (1:1 with users)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                      NOT NULL,
    avatar_url  VARCHAR(500)                NULL,
    bio         VARCHAR(1000)               NULL,
    phone       VARCHAR(30)                 NULL,
    timezone    VARCHAR(50)                 NOT NULL DEFAULT 'UTC',
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_profiles_user UNIQUE (user_id)
);

-- Backfill a default profile row for every existing user.
INSERT INTO user_profiles (user_id, timezone, created_at, updated_at)
SELECT u.id, 'UTC', now(), now()
FROM users u
WHERE NOT EXISTS (SELECT 1 FROM user_profiles p WHERE p.user_id = u.id);

-- ---------------------------------------------------------------------
-- notification_preferences (1:1 with users)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_preferences (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                       BIGINT                      NOT NULL,
    email_task_assigned           BOOLEAN                     NOT NULL DEFAULT TRUE,
    email_deadline_approaching    BOOLEAN                     NOT NULL DEFAULT TRUE,
    email_comment                 BOOLEAN                     NOT NULL DEFAULT TRUE,
    email_mention                 BOOLEAN                     NOT NULL DEFAULT TRUE,
    email_status_change           BOOLEAN                     NOT NULL DEFAULT TRUE,
    email_project_invite          BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_task_assigned          BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_deadline_approaching   BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_comment                BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_mention                BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_status_change          BOOLEAN                     NOT NULL DEFAULT TRUE,
    in_app_project_invite         BOOLEAN                     NOT NULL DEFAULT TRUE,
    updated_at                    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_prefs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_notification_prefs_user UNIQUE (user_id)
);

INSERT INTO notification_preferences (user_id, updated_at)
SELECT u.id, now()
FROM users u
WHERE NOT EXISTS (SELECT 1 FROM notification_preferences n WHERE n.user_id = u.id);

-- ---------------------------------------------------------------------
-- user_activity (append-only audit trail of account-level events)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_activity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                      NOT NULL,
    type        VARCHAR(40)                 NOT NULL,
    description VARCHAR(255)                NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_activity_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_user_activity_user    ON user_activity (user_id);
CREATE INDEX IF NOT EXISTS idx_user_activity_created ON user_activity (created_at);
