-- =====================================================================
-- V6 — Workspaces & Projects: the collaboration backbone.
-- =====================================================================

-- ---------------------------------------------------------------------
-- workspaces
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workspaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)                NOT NULL,
    description VARCHAR(500)                NULL,
    type        VARCHAR(20)                 NOT NULL,
    created_by  BIGINT                      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_workspaces_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- workspace_members
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workspace_members (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT                      NOT NULL,
    user_id      BIGINT                      NOT NULL,
    role         VARCHAR(20)                 NOT NULL,
    joined_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_workspace_members_workspace_user UNIQUE (workspace_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_workspace_members_user ON workspace_members (user_id);

-- ---------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT                      NOT NULL,
    name         VARCHAR(150)                NOT NULL,
    description  TEXT                        NULL,
    deadline     DATE                        NULL,
    created_by   BIGINT                      NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_projects_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_projects_workspace ON projects (workspace_id);

-- ---------------------------------------------------------------------
-- project_members
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT                      NOT NULL,
    user_id    BIGINT                      NOT NULL,
    role       VARCHAR(20)                 NOT NULL,
    joined_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_project_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_project_members_project_user UNIQUE (project_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members (user_id);

-- ---------------------------------------------------------------------
-- tasks: optional link to a project
-- ---------------------------------------------------------------------
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS project_id BIGINT NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks (project_id);

-- ---------------------------------------------------------------------
-- Backfill: every existing user gets a Personal Workspace (idempotent).
-- ---------------------------------------------------------------------
INSERT INTO workspaces (name, type, created_by, created_at, updated_at)
SELECT 'Personal Workspace', 'PERSONAL', u.id, now(), now()
FROM users u
WHERE NOT EXISTS (
    SELECT 1 FROM workspaces w WHERE w.created_by = u.id AND w.type = 'PERSONAL'
);

INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
SELECT w.id, w.created_by, 'OWNER', now()
FROM workspaces w
WHERE w.type = 'PERSONAL'
  AND NOT EXISTS (
    SELECT 1 FROM workspace_members wm WHERE wm.workspace_id = w.id AND wm.user_id = w.created_by
);
