-- =====================================================================
-- V7 — Advanced task fields (start date, time tracking, recurrence)
--      + task_history audit trail.
-- =====================================================================

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS start_date          DATE        NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS estimated_minutes   INTEGER     NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS actual_minutes      INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence          VARCHAR(20) NOT NULL DEFAULT 'NONE';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_end_date DATE        NULL;

CREATE TABLE IF NOT EXISTS task_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT                      NOT NULL,
    actor_id   BIGINT                      NOT NULL,
    summary    VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_history_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_history_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_task_history_task    ON task_history (task_id);
CREATE INDEX IF NOT EXISTS idx_task_history_created ON task_history (created_at);
