-- =====================================================================
-- V8 — Task assignees, watchers, and workspace-scoped tags.
-- =====================================================================

CREATE TABLE IF NOT EXISTS task_assignees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT                      NOT NULL,
    user_id     BIGINT                      NOT NULL,
    assigned_by BIGINT                      NOT NULL,
    assigned_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_assignees_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignees_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignees_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_task_assignees_task_user UNIQUE (task_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_task_assignees_user ON task_assignees (user_id);

CREATE TABLE IF NOT EXISTS task_watchers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT                      NOT NULL,
    user_id    BIGINT                      NOT NULL,
    watched_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_watchers_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_watchers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_task_watchers_task_user UNIQUE (task_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_task_watchers_user ON task_watchers (user_id);

CREATE TABLE IF NOT EXISTS tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT                     NOT NULL,
    name        VARCHAR(50)                 NOT NULL,
    color       VARCHAR(20)                 NULL,
    created_by  BIGINT                      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tags_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_tags_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_tags_workspace_name UNIQUE (workspace_id, name)
);

CREATE TABLE IF NOT EXISTS task_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT                      NOT NULL,
    tag_id     BIGINT                      NOT NULL,
    added_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT uk_task_tags_task_tag UNIQUE (task_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_task_tags_tag ON task_tags (tag_id);
