-- =====================================================================
-- V9 — Subtasks, task dependencies, comments (+ mentions), attachments.
-- =====================================================================

CREATE TABLE IF NOT EXISTS subtasks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT                      NOT NULL,
    title      VARCHAR(200)                NOT NULL,
    completed  BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_subtasks_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_subtasks_task ON subtasks (task_id);

CREATE TABLE IF NOT EXISTS task_dependencies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id            BIGINT                      NOT NULL,
    depends_on_task_id BIGINT                      NOT NULL,
    created_by         BIGINT                      NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_dependencies_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_dependencies_depends_on FOREIGN KEY (depends_on_task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_dependencies_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_task_dependencies_task_depends_on UNIQUE (task_id, depends_on_task_id)
);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_depends_on ON task_dependencies (depends_on_task_id);

CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT                      NOT NULL,
    author_id  BIGINT                      NOT NULL,
    content    TEXT                        NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_comments_task ON comments (task_id);

CREATE TABLE IF NOT EXISTS comment_mentions (
    comment_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    PRIMARY KEY (comment_id, user_id),
    CONSTRAINT fk_comment_mentions_comment FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_mentions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_comment_mentions_user ON comment_mentions (user_id);

CREATE TABLE IF NOT EXISTS attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT                      NOT NULL,
    uploaded_by  BIGINT                      NOT NULL,
    file_name    VARCHAR(255)                NOT NULL,
    file_url     VARCHAR(500)                NOT NULL,
    content_type VARCHAR(100)                NULL,
    size_bytes   BIGINT                      NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attachments_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_attachments_task ON attachments (task_id);
