-- =====================================================================
-- Task Management System - PostgreSQL schema (reference)
-- ---------------------------------------------------------------------
-- The application uses Hibernate `ddl-auto: update`, so these tables are
-- created automatically on first startup. This file documents the schema
-- explicitly and can be used to provision the database manually if you
-- prefer `ddl-auto: validate` in production.
--
-- Unlike MySQL, PostgreSQL has no `CREATE DATABASE IF NOT EXISTS`, and a
-- database cannot be created from a connection that is already inside
-- another database. Create it once, out of band, before running this
-- script or starting the app:
--
--   createdb task_manager
--   -- or, connected to the default "postgres" database:
--   CREATE DATABASE task_manager;
-- =====================================================================

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)                NOT NULL,
    email       VARCHAR(150)                NOT NULL,
    password    VARCHAR(255)                NOT NULL,          -- BCrypt hash
    role        VARCHAR(20)                 NOT NULL DEFAULT 'ROLE_USER',
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ---------------------------------------------------------------------
-- tasks
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150)                NOT NULL,
    description  TEXT                        NULL,
    priority     VARCHAR(20)                 NOT NULL DEFAULT 'MEDIUM',   -- LOW | MEDIUM | HIGH
    status       VARCHAR(20)                 NOT NULL DEFAULT 'TODO',     -- TODO | IN_PROGRESS | DONE
    due_date     DATE                        NULL,
    user_id      BIGINT                      NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tasks_user     ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);
